/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as StudySessionRouteImport } from './routes/study-session'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CareerRouteImport } from './routes/career'
import { Route as IndexRouteImport } from './routes/index'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudySessionRoute = StudySessionRouteImport.update({
  id: '/study-session',
  path: '/study-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/study-session': typeof StudySessionRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/study-session': typeof StudySessionRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/coach': typeof CoachRoute
  '/dashboard': typeof DashboardRoute
  '/growth': typeof GrowthRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/study-session': typeof StudySessionRoute
  '/tests': typeof TestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/coach'
    | '/dashboard'
    | '/growth'
    | '/legal'
    | '/login'
    | '/premium'
    | '/profile'
    | '/study-session'
    | '/tests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/coach'
    | '/dashboard'
    | '/growth'
    | '/legal'
    | '/login'
    | '/premium'
    | '/profile'
    | '/study-session'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/coach'
    | '/dashboard'
    | '/growth'
    | '/legal'
    | '/login'
    | '/premium'
    | '/profile'
    | '/study-session'
    | '/tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRoute
  CoachRoute: typeof CoachRoute
  DashboardRoute: typeof DashboardRoute
  GrowthRoute: typeof GrowthRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  StudySessionRoute: typeof StudySessionRoute
  TestsRoute: typeof TestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-session': {
      id: '/study-session'
      path: '/study-session'
      fullPath: '/study-session'
      preLoaderRoute: typeof StudySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRoute,
  CoachRoute: CoachRoute,
  DashboardRoute: DashboardRoute,
  GrowthRoute: GrowthRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  StudySessionRoute: StudySessionRoute,
  TestsRoute: TestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
